
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6IkNPT1JEMDAxIiwiY29sbGFib3JhdG9ySWQiOiI5ZjlmZWE1Yi0zMGIxLTQ2YzEtOTgzZS0yMzQyNjIzMzQwMTgiLCJyb2xlcyI6WyJST0xFX0NPT1JESU5BVE9SIl0sImV4cCI6MTc4MzM3NTM1M30.fNOu7cRfyxXqxhG-n9zFeWjaH93KlxadcLaVTTGrgqA
GET http://localhost:3003/api/v1/dogfeeding/rations
Content-Type: application/json
Authorization: Bearer {{token}}

###