spring:
  application:
    name: user-management

  Jackson:
    time-zone: America/Sao_Paulo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: false

server:
  address: 0.0.0.0
  port: 3001


logging:
  level:
    org.springframework.security: DEBUG


api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

---

#PROFILE LOCAL PARA RODAR VIA INTELLIJ
spring:
  datasource:
    url: jdbc:postgresql://localhost:${BD_USER_MANAGEMENT_PORT}/${BD_USER_MANAGEMENT_NAME}
    password: ${BD_USER_MANAGEMENT_PASSWORD}
    username: ${BD_USER_MANAGEMENT_USER}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3002/eureka
  instance:
    prefer-ip-address: true

---

#PROFILE DOCKER PARA RODAR NO DOCKER
spring:
  datasource:
    url: jdbc:postgresql://${BD_USER_MANAGEMENT_HOST}:5432/${BD_USER_MANAGEMENT_NAME}
    password: ${BD_USER_MANAGEMENT_PASSWORD}
    username: ${BD_USER_MANAGEMENT_USER}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:3002/eureka
  instance:
    prefer-ip-address: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    csrf:
      enabled: true
