### POST cadastra um novo coordenador
POST http://localhost:3003/api/v1/employees/coordinators
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6IkNPT1JEMDAxIiwibW9uaXRvcklkIjoiMjIyMjIyMjItMjIyMi0yMjIyLTIyMjItMjIyMjIyMjIyMjIyIiwicm9sZXMiOlsiUk9MRV9DT09SRElOQVRPUiJdLCJleHAiOjE3Nzg1MjMxMjJ9.K5vPhxQICpysrk3OBUGPnDMPGZcHff2J1fNXVpPe5xo

{
  "email": "coord6@dogvision.com",
  "name": "Ana Coordenadora",
  "phone": "61999999999",
  "registration": "COORD-006",
  "password": "12345678",
  "codAdmin": 1006,
  "shift": "MORNING"
}


###
