### GET busca todos os coordenadores
GET http://localhost:3003/api/v1/employees/coordinators
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6IkNPT1JELTAwMSIsInVzZXJJZCI6ImJkZDRkYmFiLWE1OTQtNGQzOC04ZGY1LWVjYjk3YTQzMWM5MSIsInJvbGVzIjpbIlJPTEVfQ09PUkRJTkFUT1IiXSwiZXhwIjoxNzc1MTUxNDAyfQ.gg36rl2PwcQbeoRh1ZO9Cm6G-HtwP17JcoXYvH-RyqE
