### DELETE remove um treinador pelo ID
DELETE http://localhost:3003/api/v1/employees/trainers/7c1d9bbd-d4f6-44eb-be93-8e4190174a45
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6IkNPT1JELTAwMSIsImV4cCI6MTc3MTg1NjExNX0.Pt38Njus31uMHVdcQ1vAN0Xr-4QzI8M7UN-wIWv7f10


###
