spring:
  application:
    name: notification

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  docker:
    compose:
      enabled: false

server:
  address: 0.0.0.0
  port: 3007

logging:
  level:
    org.springframework.security: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

---

# PROFILE LOCAL PARA RODAR VIA INTELLIJ
spring:
  datasource:
    url: jdbc:postgresql://localhost:${BD_NOTIFICATION_PORT:5432}/${BD_NOTIFICATION_NAME:notification}
    password: ${BD_NOTIFICATION_PASSWORD:postgres}
    username: ${BD_NOTIFICATION_USER:postgres}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: localhost
    port: ${RABBIT_AMQP_PORT:5672}
    password: ${RABBIT_PASSWORD:guest}
    username: ${RABBIT_USER:guest}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3002/eureka
  instance:
    prefer-ip-address: true

---

# PROFILE DOCKER PARA RODAR NO DOCKER
spring:
  datasource:
    url: jdbc:postgresql://${BD_NOTIFICATION_HOST:notification_db}:5432/${BD_NOTIFICATION_NAME:notification}
    password: ${BD_NOTIFICATION_PASSWORD:postgres}
    username: ${BD_NOTIFICATION_USER:postgres}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq
    port: ${RABBIT_AMQP_PORT:5672}
    password: ${RABBIT_PASSWORD:guest}
    username: ${RABBIT_USER:guest}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:3002/eureka
  instance:
    prefer-ip-address: true
