### PATCH atualiza os dados de um funcionário
PATCH http://localhost:3003/api/v1/employees/0ef405a0-9784-466a-95ed-7141256a9594
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6IkNPT1JELTAwMSIsInVzZXJJZCI6ImJkZDRkYmFiLWE1OTQtNGQzOC04ZGY1LWVjYjk3YTQzMWM5MSIsInJvbGVzIjpbIlJPTEVfQ09PUkRJTkFUT1IiXSwiZXhwIjoxNzczODUxODY3fQ.ReUviKbuEE-JfWj4_6oiFjgxlQ3Ao7ZYTWAtzpdq_z4

{
"email": "teste123@dogvision.com",
"phone": "61999999997"
}


###
