### POST cadastra um novo cão
POST http://localhost:3003/api/v1/dogs
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Lili",
  "age": 2,
  "race": "Labrador",
  "sex": "F",
  "status": "ADAPTACAO"

}

###
